### ISSUE TITLE
Better support for Backdrop

### ISSUE THREAD

**Issue by mlutfy** [mlutfy/hosting#32]
Consolidating Backdrop issues here:

- [ ] Do more QA of the site installation #10
- [ ] Setup cron #28
- [ ] Setup CiviCRM cron #29
- [ ] Regenerate settings on verify #24
